const mainMenu = [
    {
        name:"About US",
        url:"#"
    },    {
        name:"Services",
        url:"#"
    },
        {
        name:"Products",
        url:"#"
    },
        {
        name:"Clients",
        url:"#"
    },
        {
        name:"Training",
        url:"#"
    },
        {
        name:"Career",
        url:"#"
    },
        {
        name:"Contact Us",
        url:"#"
    }];

const menu={
    Services : [
        {
            name:"App Development",
            url:"#",
            subMenu:[
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                }
            ]
        },
        {
            name:"Big Data",
            url:"#",
            subMenu:[
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                }
            ]
        },
        {
            name:"Cloud",
            url:"#",
            subMenu:[
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                }
            ]
        },
        {
            name:"Customer Relation Management",
            url:"#",
            subMenu:[
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                }
            ]
        },
        {
            name:"Data&nbsp;warehousing, BI &amp; Reporting",
            url:"#",
            subMenu:[
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                },
                {
                    name:".Net",
                    url:"#"
                }
            ]
        },
        {
            name:"IT Support",
            url:"#",
            subMenu:[]
        }
    ],

Products:[
            {
            name:"Cloud Funnel",
            url:"#",
            subMenu:[]
        },
                {
            name:"IT Support",
            url:"#",
            subMenu:[]
        }
]    
}